require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MicrohoodsController do

  def mock_microhood(stubs={})
    @mock_microhood ||= mock_model(Microhood, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all microhoods as @microhoods" do
      Microhood.stub(:all) { [mock_microhood] }
      get :index
      assigns(:microhoods).should eq([mock_microhood])
    end
  end

  describe "GET show" do
    it "assigns the requested microhood as @microhood" do
      Microhood.stub(:find).with("37") { mock_microhood }
      get :show, :id => "37"
      assigns(:microhood).should be(mock_microhood)
    end
  end

  describe "GET new" do
    it "assigns a new microhood as @microhood" do
      Microhood.stub(:new) { mock_microhood }
      get :new
      assigns(:microhood).should be(mock_microhood)
    end
  end

  describe "GET edit" do
    it "assigns the requested microhood as @microhood" do
      Microhood.stub(:find).with("37") { mock_microhood }
      get :edit, :id => "37"
      assigns(:microhood).should be(mock_microhood)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created microhood as @microhood" do
        Microhood.stub(:new).with({'these' => 'params'}) { mock_microhood(:save => true) }
        post :create, :microhood => {'these' => 'params'}
        assigns(:microhood).should be(mock_microhood)
      end

      it "redirects to the created microhood" do
        Microhood.stub(:new) { mock_microhood(:save => true) }
        post :create, :microhood => {}
        response.should redirect_to(microhood_url(mock_microhood))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved microhood as @microhood" do
        Microhood.stub(:new).with({'these' => 'params'}) { mock_microhood(:save => false) }
        post :create, :microhood => {'these' => 'params'}
        assigns(:microhood).should be(mock_microhood)
      end

      it "re-renders the 'new' template" do
        Microhood.stub(:new) { mock_microhood(:save => false) }
        post :create, :microhood => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested microhood" do
        Microhood.stub(:find).with("37") { mock_microhood }
        mock_microhood.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :microhood => {'these' => 'params'}
      end

      it "assigns the requested microhood as @microhood" do
        Microhood.stub(:find) { mock_microhood(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:microhood).should be(mock_microhood)
      end

      it "redirects to the microhood" do
        Microhood.stub(:find) { mock_microhood(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(microhood_url(mock_microhood))
      end
    end

    describe "with invalid params" do
      it "assigns the microhood as @microhood" do
        Microhood.stub(:find) { mock_microhood(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:microhood).should be(mock_microhood)
      end

      it "re-renders the 'edit' template" do
        Microhood.stub(:find) { mock_microhood(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested microhood" do
      Microhood.stub(:find).with("37") { mock_microhood }
      mock_microhood.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the microhoods list" do
      Microhood.stub(:find) { mock_microhood }
      delete :destroy, :id => "1"
      response.should redirect_to(microhoods_url)
    end
  end

end
